config/routes.rb
Rails.application.routes.draw do

  get 'bookrooms/slots', as: :bookroom_slots
  post 'bookrooms/slots'
  # get 'users/new'

  get 'transactions', to: 'users#transactions'



  # get 'users/index'

  #  temporarily change to show react abilities. Using root 'static#home will redirect to nick's user page.
  # Using root 'statics#home will redirect to daniel's react page
  root 'static#home'
  # root 'statics#home'

  resources :meetingrooms
  resources :bookrooms
  resources :adverts
  resources :spaces
  resources :myadverts, only: [:index, :edit, :destroy]

  # resources :bookevents

  # get 'bookevents', to: 'bookevents#show'
   post 'bookevents', to: 'bookevents#create'

  resources :create_users, :controller => 'users'
  # :only =>[:show]

  devise_for :users,
          path: '',
          path_names: {
            sign_in: 'login',
            sign_out: 'logout',
            sign_up: 'register'
          }

  resources :events

  post 'event', to:'event#booktix'
end

app/models/advert.rb
class Advert < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/bookevent.rb
class Bookevent < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/bookroom.rb
class Bookroom < ApplicationRecord
  belongs_to :meetingroom
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :bookevents

end

app/models/meetingroom.rb
class Meetingroom < ApplicationRecord
  has_many :bookrooms
end

app/models/role.rb
# class Role < ApplicationRecord
#   has_and_belongs_to_many :users, :join_table => :users_roles
#
#   belongs_to :resource,
#              :polymorphic => true,
#              :optional => true
#
#   validates :resource_type,
#             :inclusion => { :in => Rolify.resource_types },
#             :allow_nil => true
#
#   scopify
# end

app/models/slot.rb
class Slot < ApplicationRecord
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :adverts
  has_many :spaces
  has_many :bookrooms
  has_many :bookevents
end

app/controllers/myadverts_controller.rb
class MyadvertsController < ApplicationController

  def index
    @myadverts = Advert.where("user_id= #{current_user.id}")
  end

  def edit
    @advert = Advert.find(params[:id])
  end

  def destroy
    promo_to_delete = Advert.find(params[:id])
    promo_to_delete.destroy
    redirect_to myadverts_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :isAdmin, except: [:show, :transactions]

  def index
    @user = User.all
  end

  def show
    @bookings = Bookroom.where(user_id: @user)

    @user = User.find_by_id(params[:id])
    @booking_groups_by_date_start =
    Bookroom.select('user_id, date_start, count(*) as total_bookings')
            .group('user_id', 'date_start')
            .having('user_id = ?', current_user.id)

    @allBookingsPerGroup = []
    @booking_groups_by_date_start.each do |group|
      @allBookingsPerGroup << Bookroom.where(user_id: current_user.id, date_start: group.date_start)
    end

    # @bookings_date = Bookroom.where(user_id: @user, date_start: "09/09/2017")
    # @dategroup = Bookroom.includes(:date_start)
    @events = Bookevent.where(user_id: @user)
    @all_events = Event.where('event_start>?',
    DateTime.now.change(:offset => "+0000"))

    # @bookings = Bookroom.where(user_id: @user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:name, :email, :password, :isAdmin))
    redirect_to create_users_path
  end

  def transactions
    user = current_user
    @reservations = Bookroom.where(user_id: user)
  end

  private

  def isAdmin
    if !current_user.isAdmin
      redirect_to '/'
    end
  end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/bookrooms_helper.rb
module BookroomsHelper
end

app/helpers/meetingrooms_helper.rb
module MeetingroomsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/myadverts/edit.html.erb
<h1>Edit My Promos</h1>
<div class="container">

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<%= form_for @advert, :url => advert_path(@advert), :method => :put  do |f| %>
<div class="field">

  <div class="center">
    <img class='advert_image' onclick="openEventWidgets()" src="http://i.imgur.com/hFjTK8K.png" data-toggle="tooltip" data-placement="right" title="Click to upload event image">
  </div>

  <h4><%= f.label :title %> :</h4>
  <%= f.text_field :title, autofocus: true, required: true, class: "form-control"  %>
</div>

<div class="">
  <h4><%= f.label :description %>:</h4>
  <p><%= f.text_area :description,size: "100x5", required: true, class: "form-control" %> </p>
</div>

  <%= f.hidden_field :advert_image %>

<div class="center">
    <%= f.submit "Create", class: "btn btn-primary" %>
</div>

  <br>
<% end %>

</div>

app/views/myadverts/index.html.erb
<div class="container center">

  <h1>My Promos</h1>

  <% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
  <% end %>

  <% @myadverts.each do |advert| %>
  <div class="card-group d-inline" style="width: 55rem;">

    <div class="card d-inline-block">

      <% if advert.advert_image.to_s == "" %>
      <%= image_tag 'http://i.imgur.com/hFjTK8K.png', size: "370x300" %>
    <% else %>
      <%= image_tag advert.advert_image, size: "370x300" %>
      <% end %>

      <h3>Title:
        <%= advert.title %>
      </h3>

      <% if !advert.description %>
      <h4>
        Description : No description</h4>
      <% elsif (advert.description.split.size >= 5) %>
      <h4>Description:<%= advert.description[/(\S+\s+){5}/].strip  %>...</h4>
    <% else %>
      <h4>
        Description :
        <%= advert.description %></h4>
      <% end %>

      <%= link_to "Edit", edit_myadvert_path(advert), class: "btn btn-primary" %>
      <%= link_to "Delete", myadvert_path(advert), method: :delete, class: "btn btn-primary" %>

    </div>
  </div>

  <% end %>

</div>