config/routes.rb
Rails.application.routes.draw do

  get 'bookrooms/slots', as: :bookroom_slots
  post 'bookrooms/slots'
  # get 'users/new'

  get 'transactions', to: 'users#transactions'



  # get 'users/index'

  #  temporarily change to show react abilities. Using root 'static#home will redirect to nick's user page.
  # Using root 'statics#home will redirect to daniel's react page
  root 'static#home'
  # root 'statics#home'

  resources :meetingrooms
  resources :bookrooms
  resources :adverts
  resources :spaces
  resources :myadverts, only: [:index, :edit, :destroy]

  # resources :bookevents

  # get 'bookevents', to: 'bookevents#show'
   post 'bookevents', to: 'bookevents#create'

  resources :create_users, :controller => 'users'
  # :only =>[:show]

  devise_for :users,
          path: '',
          path_names: {
            sign_in: 'login',
            sign_out: 'logout',
            sign_up: 'register'
          }

  resources :events

  post 'event', to:'event#booktix'
end

app/models/advert.rb
class Advert < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/bookevent.rb
class Bookevent < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/bookroom.rb
class Bookroom < ApplicationRecord
  belongs_to :meetingroom
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :bookevents

end

app/models/meetingroom.rb
class Meetingroom < ApplicationRecord
  has_many :bookrooms
end

app/models/role.rb
# class Role < ApplicationRecord
#   has_and_belongs_to_many :users, :join_table => :users_roles
#
#   belongs_to :resource,
#              :polymorphic => true,
#              :optional => true
#
#   validates :resource_type,
#             :inclusion => { :in => Rolify.resource_types },
#             :allow_nil => true
#
#   scopify
# end

app/models/slot.rb
class Slot < ApplicationRecord
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :adverts
  has_many :spaces
  has_many :bookrooms
  has_many :bookevents
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :isAdmin, except: [:show, :transactions]

  def index
    @user = User.all
  end

  def show
    @bookings = Bookroom.where(user_id: @user)

    @user = User.find_by_id(params[:id])
    @booking_groups_by_date_start =
    Bookroom.select('user_id, date_start, count(*) as total_bookings')
            .group('user_id', 'date_start')
            .having('user_id = ?', current_user.id)

    @allBookingsPerGroup = []
    @booking_groups_by_date_start.each do |group|
      @allBookingsPerGroup << Bookroom.where(user_id: current_user.id, date_start: group.date_start)
    end

    # @bookings_date = Bookroom.where(user_id: @user, date_start: "09/09/2017")
    # @dategroup = Bookroom.includes(:date_start)
    @events = Bookevent.where(user_id: @user)
    @all_events = Event.where('event_start>?',
    DateTime.now.change(:offset => "+0000"))

    # @bookings = Bookroom.where(user_id: @user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:name, :email, :password, :isAdmin))
    redirect_to create_users_path
  end

  def transactions
    user = current_user
    @reservations = Bookroom.where(user_id: user)
  end

  private

  def isAdmin
    if !current_user.isAdmin
      redirect_to '/'
    end
  end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/bookrooms_helper.rb
module BookroomsHelper
end

app/helpers/meetingrooms_helper.rb
module MeetingroomsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/create_user/new.html.erb
<h1>Creating User</h1>

<%= form_for :user do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<footer>
    <div class="footer" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> About Us </h3>
                    <ul>
                        <li> <a href="https://github.com/ddanielnp"> Daniel Lim </a> </li>
                        <li> <a href="https://github.com/merejarvis"> Azmeer </a> </li>
                        <li> <a href="https://github.com/nicoalee"> Nicholas Lee </a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Mission </h3>
                    <ul>
                        <li> <a href="#"> Lorem Ipsum </a> </li>
                        <li> <a href="#"> Lorem Ipsum </a> </li>
                        <li> <a href="#"> Lorem Ipsum </a> </li>
                        <li> <a href="#"> Lorem Ipsum </a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Why Hatchpodz </h3>
                    <ul>
                      <li> <a href="#"> Find a startup </a> </li>
                      <li> <a href="#"> Organize events </a> </li>
                        <li> <a href="#"> Referral Program </a> </li>
                        <li> <a href="#"> Broker Partnership </a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> FAQ </h3>
                    <ul>
                        <li> <a href="#"> Press </a> </li>
                        <li> <a href="#"> Blogs </a> </li>
                        <li> <a href="#"> Careers </a> </li>
                        <li> <a href="#"> Advertising </a> </li>
                    </ul>
                </div>
                <div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
                    <h3> Sign up with us </h3>
                    <ul>
                        <li>
                            <div class="input-append newsletter-box text-center">
                                <input type="text" class="full text-center" placeholder="Email ">
                                <button class="btn  bg-gray" type="button"> Send me updates <i class="fa fa-long-arrow-right"> </i> </button>
                            </div>
                        </li>
                    </ul>
                    <ul class="social">
                        <li> <a href="#"> <i class=" fa fa-facebook">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-twitter">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-google-plus">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-pinterest">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-youtube">   </i> </a> </li>
                    </ul>
                </div>
            </div>
            <!--/.row-->
        </div>
        <!--/.container-->
    </div>
    <!--/.footer-->

    <div class="footer-bottom">
        <div class="container">
            <p class="pull-left"> Copyright © Footer 2014. All right reserved. </p>
            <div class="pull-right">
                <ul class="nav nav-pills payments">
                    <li><i class="fa fa-cc-visa"></i></li>
                    <li><i class="fa fa-cc-mastercard"></i></li>
                    <li><i class="fa fa-cc-amex"></i></li>
                    <li><i class="fa fa-cc-paypal"></i></li>
                </ul>
            </div>
        </div>
    </div>
    <!--/.footer-bottom-->
</footer>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <a class="navbar-brand" href="/">
    <%= image_tag 'eggs.png', class: 'd-inline-block align-top', width: '30', height: '30' %>
    <!-- <img src="eggs.png" width="30" height="30" class="d-inline-block align-top" alt=""> -->
    Hatchpodz
  </a>



  <div id="navbarNavDropdown" class="navbar-collapse collapse">






    <% if current_user %>

    <% if current_user.isAdmin %>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Users</a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/create_users">View/ Manage Users</a>
          <a class="dropdown-item" href="/create_users/new">Create New User</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Events</a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/events">View/ Manage Events</a>
          <a class="dropdown-item" href="/events/new">Create New Event</a>
        </div>
      </li>
    </ul>

    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Spaces</a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/spaces">View/ Manage Spaces</a>
          <a class="dropdown-item" href="/spaces/new">Create New Space</a>
        </div>
      </li>
    </ul>

    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Meeting rooms</a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/meetingrooms">View/ Manage Meeting Rooms</a>
          <a class="dropdown-item" href="/meetingrooms/new">Create a New Meeting Room</a>
        </div>
      </li>
    </ul>

    <ul class="navbar-nav mr-auto">

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">MarketPlace</a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/adverts">All Promos</a>
          <a class="dropdown-item" href="/adverts/new">Create Promo</a>
        </div>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/bookrooms/new">Book a Room
          <span class="sr-only">(current)</span>
        </a>
      </li>
    </ul>
    <% else %>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">MarketPlace</a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/adverts">All Promos</a>
          <a class="dropdown-item" href="/adverts/new">Create Promo</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/events">Events
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/bookrooms/new">Book a Room
          <span class="sr-only">(current)</span>
        </a>
      </li>
    </ul>

    <% end %>


    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hello,
          <%= current_user.email %></a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "My profile", create_user_path(current_user.id), class: "dropdown-item" %>
          <%= link_to "Manage my promos", myadverts_path, class: "dropdown-item" %>

          <a class="dropdown-item" href="/transactions">My transactions</a>
        </div>
      </li>
      <% end %>
    </ul>

    <ul class="navbar-nav">
      <% if current_user %>
      <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link btn btn-outline-secondary' %>
      </li>
    <% else %>
      <li class="nav-item">
        <a class="nav-link btn btn-outline-secondary" href="/login">Login</a>
      </li>
      <% end %>
    </ul>

  </div>
</nav>