config/routes.rb
Rails.application.routes.draw do

  get 'bookrooms/slots', as: :bookroom_slots
  post 'bookrooms/slots'
  # get 'users/new'

  get 'transactions', to: 'users#transactions'



  # get 'users/index'

  #  temporarily change to show react abilities. Using root 'static#home will redirect to nick's user page.
  # Using root 'statics#home will redirect to daniel's react page
  root 'static#home'
  # root 'statics#home'

  resources :meetingrooms
  resources :bookrooms
  resources :adverts
  resources :spaces
  resources :myadverts, only: [:index, :edit, :destroy]

  # resources :bookevents

  # get 'bookevents', to: 'bookevents#show'
   post 'bookevents', to: 'bookevents#create'

  resources :create_users, :controller => 'users'
  # :only =>[:show]

  devise_for :users,
          path: '',
          path_names: {
            sign_in: 'login',
            sign_out: 'logout',
            sign_up: 'register'
          }

  resources :events

  post 'event', to:'event#booktix'
end

app/models/advert.rb
class Advert < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/bookevent.rb
class Bookevent < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/bookroom.rb
class Bookroom < ApplicationRecord
  belongs_to :meetingroom
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :bookevents

end

app/models/meetingroom.rb
class Meetingroom < ApplicationRecord
  has_many :bookrooms
end

app/models/role.rb
# class Role < ApplicationRecord
#   has_and_belongs_to_many :users, :join_table => :users_roles
#
#   belongs_to :resource,
#              :polymorphic => true,
#              :optional => true
#
#   validates :resource_type,
#             :inclusion => { :in => Rolify.resource_types },
#             :allow_nil => true
#
#   scopify
# end

app/models/slot.rb
class Slot < ApplicationRecord
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :adverts
  has_many :spaces
  has_many :bookrooms
  has_many :bookevents
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :isAdmin, except: [:index, :show]

  def index
    @all_events = Event.where('event_start>?', DateTime.now.change(:offset => "+0000"))
  end

  def create
    # render json: params
    time2 = params[:event][:event_end]
    time = params[:event][:event_start]

# convert to seconds and add 8h time difference
    if (DateTime.parse(time).to_i > DateTime.now.to_i + 28800)

      if (DateTime.parse(time2) > DateTime.parse(time))
        new_event = Event.create(params.require(:event).permit(:title,:description,:venue,:total_slots,:price_pax,:event_start,:event_end,:event_image))
        new_event.remaining_slots = params[:event][:total_slots]
        new_event.save!

        redirect_to events_path
      else
        flash[:notice] ='End date/ time must be greater than start date/time'
        redirect_to new_event_path
      end

    else
      flash[:notice] ='Start date/time must be greater than current time'
      redirect_to new_event_path
    end
  end

  def new
    @new_event = Event.new
  end

  def edit
    @current_event = Event.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
    if @event.event_start < DateTime.now.change(:offset => "+0000")
      redirect_to '/events'
    end
    @new_reservation = Bookevent.new
    @current_booking = Bookevent.where("event_id = #{params[:id]}").sum(:no_pax)
  end

  def update
    # render json: params
    to_update = Event.find(params[:id])
    new_details = params.require(:event).permit(:title,:description,:venue,:total_slots,:price_pax,:event_start,:event_end,:event_image)
    to_update.update(new_details)
    flash[:notice] ='Event details successfully changed'
    redirect_to events_path
  end

  def destroy
    # render json: params
    event_to_delete = Event.find(params[:id])
    bookings_to_delete = Bookevent.where(event_id: params[:id])
    bookings_to_delete.each do |i|
      i.destroy
    end
    event_to_delete.destroy
    redirect_to events_path
  end

  private
  def isAdmin
    if !current_user.isAdmin
      redirect_to '/events'
    end
  end

end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :isAdmin
  before_action :check_valid_member,
    only: [:update]
  before_action :check_valid_date,
    only: [:update]

  def index
    @spaces = Space.all.order(:space_type)
  end

  def show
    @space = Space.find_by_id(params[:id])
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.create(params.require(:space).permit(:space_type, :user_id, :date_start, :date_end))
    # @Space.save
    redirect_to spaces_path
  end

  def edit
    # render json: Space.find(params[:id])
      @current_space = Space.find(params[:id])
  end

  def destroy
    space_to_delete = Space.find(params[:id])
    space_to_delete.destroy
    redirect_to spaces_path

  end

  def update
    # render json: params
    to_update = Space.find(params[:id])
    new_details = params.require(:space).permit(:space_type, :user_id, :date_start, :date_end)
    to_update.update(new_details)
    flash[:notice] ='Details successfully changed'

    redirect_to spaces_path
  end

  private

  def check_valid_member
    if !User.find_by_id(params[:space][:user_id])
      flash[:notice1] = "No user by that ID"
      redirect_to edit_space_path(params[:id])
    end
  end

  def check_valid_date
    if Date.today > Date.parse(params[:space][:date_start]) ||
       Date.today > Date.parse(params[:space][:date_end]) ||
       Date.parse(params[:space][:date_start]) > Date.parse(params[:space][:date_end]) ||
       (Date.parse(params[:space][:date_end]) - Date.parse(params[:space][:date_start])) <= 10
      flash[:notice2] = "Invalid Date"
      redirect_to edit_space_path(params[:id])
    end
  end

  def isAdmin
    if !current_user.isAdmin
      redirect_to '/'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :isAdmin, except: [:show, :transactions]

  def index
    @user = User.all
  end

  def show
    @bookings = Bookroom.where(user_id: @user)

    @user = User.find_by_id(params[:id])
    @booking_groups_by_date_start =
    Bookroom.select('user_id, date_start, count(*) as total_bookings')
            .group('user_id', 'date_start')
            .having('user_id = ?', current_user.id)

    @allBookingsPerGroup = []
    @booking_groups_by_date_start.each do |group|
      @allBookingsPerGroup << Bookroom.where(user_id: current_user.id, date_start: group.date_start)
    end

    # @bookings_date = Bookroom.where(user_id: @user, date_start: "09/09/2017")
    # @dategroup = Bookroom.includes(:date_start)
    @events = Bookevent.where(user_id: @user)
    @all_events = Event.where('event_start>?',
    DateTime.now.change(:offset => "+0000"))

    # @bookings = Bookroom.where(user_id: @user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:name, :email, :password, :isAdmin))
    redirect_to create_users_path
  end

  def transactions
    user = current_user
    @reservations = Bookroom.where(user_id: user)
  end

  private

  def isAdmin
    if !current_user.isAdmin
      redirect_to '/'
    end
  end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/bookrooms_helper.rb
module BookroomsHelper
end

app/helpers/meetingrooms_helper.rb
module MeetingroomsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assets/edit.html.erb
<h1>Edit Asset/ Assign User</h1>
<h5><%= flash[:member_error] %></h5>
<h5><%= flash[:date_error] %></h5>
<%#= link_to "See All Assets", spaces_path %>
<br>

<em><h6>Minimum booking is 10 days</h6></em>
<%= form_for @current_asset, url: edit_space_path(@current_asset) do |f| %>

  <%= f.select :asset_type, options_for_select(["Office", "Desk", "Hotdesk"]) %>
  <br>
  <br>
  <%= f.label "User ID:" %>
  <%= f.number_field :user_id %>
  <br>
  <br>
  <div class="row">
    <div class='col-sm-6'>
      <div class="form-group">
        <%= f.label :date_start %> :
        <%= f.text_field :date_start, id: 'bookRoomDateStart' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class='col-sm-6'>
      <div class="form-group">
        <%= f.label :date_end %> :
        <%= f.text_field :date_end, id: 'bookRoomDateEnd' %>
      </div>
    </div>
  </div>

  <%= f.submit %>
<% end %>

app/views/assets/new.html.erb
<h1>Create New Asset</h1>
<!-- <h5><%#= flash[:member_error] %></h5>
<h5><%#= flash[:date_error] %></h5>
<%#= link_to "See All Assets", spaces_path %>
<br> -->

<!-- <em><h6>Minimum booking is 10 days</h6></em> -->

<%= form_for @asset, url: spaces_path do |f| %>
  <%= f.select :asset_type, options_for_select(["Office", "Desk", "Hotdesk"]) %>

<div class="field">
  <%= f.submit "Create", class: "btn btn-primary" %>

</div>
    <% end %>

app/views/events/edit.html.erb
<h1>Update an event</h1>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<!-- <p>Upload Event Image</p>
  <div class="center">
     <div class="input-field inline">
       <img onclick="openEventWidget()" src="http://i.imgur.com/hFjTK8K.png" class="event_image">
       <p>Click on image above to upload or change</p>
     </div>
   </div> -->

<br><br>
  <%= form_for @current_event do |f| %>

  <div class="">
    <p><%= f.label :Title %>:</p>
    <p><%= f.text_field :title, required: true, autofocus: true %></p>
  </div>

  <div style="overflow:hidden;">
    <div class="form-group">
      <div class="row">
        <div class="col-md-8">
          <p><%= f.label :Start %>:</p>
          <p><%= f.text_field :event_start, required: true, id: 'datetimepickerstart' %></p>
        </div>
      </div>
    </div>
  </div>

  <div style="overflow:hidden;">
    <div class="form-group">
      <div class="row">
        <div class="col-md-8">
          <p><%= f.label :End %>:</p>
          <p><%= f.text_field :event_end, required: true, id: 'datetimepickerend' %></p>
        </div>
      </div>
    </div>
  </div>

  <div class="">
    <p><%= f.label :Venue %>:</p>
    <p><%= f.text_field :venue, required: true %></p>
  </div>

  <div class="">
    <p><%= f.label :total_slots %>:</p>
    <p><%= f.number_field :total_slots, :min => 1, required: true %></p>
  </div>

  <div class="">
    <p><%= f.label :price_pax %>:</p>
    <p><%= f.number_field :price_pax, :min => 0, required: true  %></p>
  </div>

  <div class="">
    <p><%= f.label :Description %>:</p>
    <p><%= f.text_area :description, size: "100x15", required: true %></p>
  </div>

<div class="">
  <p>Event Image: </p>
    <div class="center">
       <div class="input-field inline">
         <img onclick="openEventWidget()" src="http://i.imgur.com/hFjTK8K.png" class="event_image">

       </div>
     </div>
</div>

<%= f.hidden_field :event_image %>

  <div class="actions">
    <%= f.submit "Create Event", class: "btn btn-primary" %>
    <br>
  </div>

  <% end %>

app/views/events/index.html.erb
<div class="container center">
  <h1>Events Calendar</h1>


  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>


  <% @all_events.each do |i|  %>
  <div class="card-group d-inline" style="width: 55rem;">

  <div class="card d-inline-block">

  <% if i.event_image.to_s == "" %>
  <%= image_tag 'http://i.imgur.com/hFjTK8K.png', size: "370x300" %>
   <%  else %>
    <%= image_tag i.event_image, size: "370x300" %>
  <% end %>

  <h3> Title : <%= i.title %> </h3>

<% if !i.description %>
<h4> Description : No description</h4>
<% elsif (i.description.split.size >= 5) %>
<h4> Description : <%= i.description[/(\S+\s+){5}/].to_s.strip %>... </h4>
<% else %>
<h4> Description : <%= i.description %></h4>
<% end %>

  <p> Start : <%= i.event_start.strftime('%e %b %y, %l:%M %p') %> || End : <%= i.event_end.strftime('%e %b %y, %l:%M %p') %></p>

  <% if (i.remaining_slots > 0) %>
    <p>Remaining slots : <%= i.remaining_slots %> </p>
  <% else %>
    <p> **FULLY BOOKED** </p>
  <% end %>

  <%= link_to "More details/ Book", event_path(i), class: "btn btn-primary" %>
  <% if current_user.isAdmin == true %>
  <%= link_to "Edit Event", edit_event_path(i), class: "btn btn-primary"  %>
  <%= link_to "Delete", event_path(i), method: :delete, class: "btn btn-primary" %>
  <% end %>
</div>
</div>
  <% end %>

</div>

app/views/events/new.html.erb
<h1>Create an event</h1>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>


<br><br>
  <%= form_for @new_event do |f| %>

  <div class="">
    <p><%= f.label :Title %>:</p>
    <p><%= f.text_field :title, required: true, autofocus: true %></p>
  </div>

  <div style="overflow:hidden;">
    <div class="form-group">
      <div class="row">
        <div class="col-md-8">
          <p><%= f.label :Start %>:</p>
          <p><%= f.text_field :event_start, required: true, id: 'datetimepickerstart' %></p>
        </div>
      </div>
    </div>
  </div>

  <div style="overflow:hidden;">
    <div class="form-group">
      <div class="row">
        <div class="col-md-8">
          <p><%= f.label :End %>:</p>
          <p><%= f.text_field :event_end, required: true, id: 'datetimepickerend' %></p>
        </div>
      </div>
    </div>
  </div>

  <div class="">
    <p><%= f.label :Venue %>:</p>
    <p><%= f.text_field :venue, required: true %></p>
  </div>

  <div class="">
    <p><%= f.label :total_slots %>:</p>
    <p><%= f.number_field :total_slots, :min => 1, required: true %></p>
  </div>

  <div class="">
    <p><%= f.label :price_pax %>:</p>
    <p><%= f.number_field :price_pax, :min => 0, required: true  %></p>
  </div>

  <div class="">
    <p><%= f.label :Description %>:</p>
    <p><%= f.text_area :description, size: "100x5", required: true %></p>
  </div>

<div class="">
       <div class="input-field inline">
         <img onclick="openEventWidget()" src="http://i.imgur.com/hFjTK8K.png" class="event_image">

     </div>
</div>

<%= f.hidden_field :event_image %>

  <div class="actions">
    <%= f.submit "Create Event", class: "btn btn-primary" %>
    <br>
  </div>

  <% end %>

app/views/events/show.html.erb
<div class="container">

  <h2>Event Details & Booking</h2>

  <% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
  <% end %>

  <% if @event.event_image %>
  <%= image_tag @event.event_image %>
<% else %>
  <%= image_tag 'http://i.imgur.com/hFjTK8K.png', size: "370x300" %>
  <% end %>

  <h3><%= @event.title %></h3>

  <h4>Starts :
    <%= @event.event_start.strftime('%e %b %y, %l:%M %p') %>
    || Ends :
    <%= @event.event_end.strftime('%e %b %y, %l:%M %p') %>
  </h4>

  <h4>Venue :
    <%= @event.venue %></h4>

  <h4>
    <%= @event.remaining_slots %> tickets left /
    <%= @event.total_slots %> tickets</h4>
</h4>

<% if @event.price_pax == 0 %>
<h4>Price per ticket : FREE ADMISSION!</h4>
<% else %>
<h4>Price per ticket :
  <%= @event.price_pax %></h4>
<% end %>

<div class="">
  <h4>Description :</h4>
  <h4><%= @event.description %></h4>
</div>

<% if @event.remaining_slots > 0 %>
<div class="">
  <h2>BOOK TICKETS</h2>
  <%= form_for @new_reservation do |f| %>
  <%= f.label :Number_tix %>
  <%= f.number_field :no_pax, min: 1 %>
  <%= f.hidden_field :event_id, value: @event.id %>

  <div class="actions">
    <br>
    <%= f.submit "Book tickets", class: "btn btn-primary" %>
  </div>

  <% end %>
</div>
<% end %>

<p>*Please note that all bookings are non- refundable.</p>



</div>

app/views/layouts/events/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  </body>
</html>

app/views/layouts/events/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>new form</h1>
  </body>
</html>

app/views/layouts/events/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>show single event page</h1>
  </body>
</html>

app/views/spaces/edit.html.erb
<h1>Edit Asset/ Assign User</h1>
<h5><%= flash[:notice1] %></h5>
<h5><%= flash[:notice2] %></h5>
<%#= link_to "See All Assets", spaces_path %>
<br>

<em><h6>Minimum booking is 10 days</h6></em>
<%= form_for @current_space do |f| %>

  <%= f.select :space_type, options_for_select(["Office", "Desk", "Hotdesk"]) %>
  <br>
  <br>
  <%= f.label "User ID:" %>
  <%= f.number_field :user_id %>
  <br>
  <br>
  <div class="row">
    <div class='col-sm-6'>
      <div class="form-group">
        <%= f.label :date_start %> :
        <%= f.text_field :date_start, id: 'bookRoomDateStart' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class='col-sm-6'>
      <div class="form-group">
        <%= f.label :date_end %> :
        <%= f.text_field :date_end, id: 'bookRoomDateEnd' %>
      </div>
    </div>
  </div>

  <%= f.submit %>
<% end %>

app/views/spaces/index.html.erb
<h1>All Spaces</h1>

<% @spaces.each do |space| %>
<div class="field">
  <p> Space ID: <%= space.id %> </p>
  <p> Space Type: <%= space.space_type %></p>
  <% if space.date_start && space.date_end %>
  <p> Start Date: <%= space.date_start.to_date.strftime('%e %b %Y') %></p>
  <p> End Date: <%= space.date_end.to_date.strftime('%e %b %Y')%></p>
  <% end %>


  <% if space.user_id %>
  <p> Assigned User: <%= space.user.name %></p>
  <% else %>
  <p> Assigned User: NIL</p>
  <% end %>

  <%= link_to "Edit Space/ Assign User", edit_space_path(space), class: "btn btn-primary"  %>
  <%= link_to "Delete", space_path(space), method: :delete, class: "btn btn-primary" %>
</div>
<% end %>

app/views/spaces/new.html.erb
<h1>Create New Asset</h1>
<!-- <h5><%#= flash[:member_error] %></h5>
<h5><%#= flash[:date_error] %></h5>
<%#= link_to "See All Assets", spaces_path %>
<br> -->

<!-- <em><h6>Minimum booking is 10 days</h6></em> -->

<%= form_for @space do |f| %>
  <%= f.select :space_type, options_for_select(["Office", "Desk", "Hotdesk"]) %>

<div class="field">
  <%= f.submit "Create", class: "btn btn-primary" %>

</div>
    <% end %>

app/views/spaces/show.html.erb
<h1>See individual Asset</h1>

<h3>Member Name</h3>
<h6><%= @asset.user.name %></h6>

<h3>Asset Type</h3>
<%= @asset.asset_type %>

<h3>Member ID</h3>
<%= @asset.id%>

<br>
<br>

<%= link_to "Back", :back %>