config/routes.rb
Rails.application.routes.draw do

  get 'bookrooms/slots', as: :bookroom_slots
  post 'bookrooms/slots'
  # get 'users/new'

  get 'transactions', to: 'users#transactions'



  # get 'users/index'

  #  temporarily change to show react abilities. Using root 'static#home will redirect to nick's user page.
  # Using root 'statics#home will redirect to daniel's react page
  root 'static#home'
  # root 'statics#home'

  resources :meetingrooms
  resources :bookrooms
  resources :adverts
  resources :spaces
  resources :myadverts, only: [:index, :edit, :destroy]

  # resources :bookevents

  # get 'bookevents', to: 'bookevents#show'
   post 'bookevents', to: 'bookevents#create'

  resources :create_users, :controller => 'users'
  # :only =>[:show]

  devise_for :users,
          path: '',
          path_names: {
            sign_in: 'login',
            sign_out: 'logout',
            sign_up: 'register'
          }

  resources :events

  post 'event', to:'event#booktix'
end

app/models/advert.rb
class Advert < ApplicationRecord
  belongs_to :user
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  def index
    @adverts = Advert.all
  end

  def show
    @advert = Advert.find_by_id(params[:id])
    @edit_advert_by_id = @advert.user_id
  end

  def new
    @advert = Advert.new
  end

  def create
    if params[:advert][:title] == "" || params[:advert][:title] == ""

      flash[:notice] =' Please input title & description'
      redirect_to new_advert_path
    else
      @advert = Advert.create(params.require(:advert).permit(:description, :advert_image, :title))
      # if params[:advert][:advert_image] == ''
      #   @advert.advert_image = "http://i.imgur.com/hFjTK8K.png"
      # end
      @advert.user_id = current_user.id
      @advert.save

      redirect_to adverts_path
    end
  end

  def edit
    @current_advert = Advert.find(params[:id])
  end

  def update
    # render json: params
    to_update = Advert.find(params[:id])
    new_details = params.require(:advert).permit(:title, :description, :advert_image)
    to_update.update(new_details)
    flash[:notice] ='Details successfully changed'

    redirect_to myadverts_path
  end

  def destroy
  end

end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/views/adverts/edit.html.erb
<h1>Edit Promo</h1>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= form_for @current_advert do |f| %>
<div class="field">

  <div class="center">
    <img class='advert_image' onclick="openEventWidgets()" src="http://i.imgur.com/hFjTK8K.png" data-toggle="tooltip" data-placement="right" title="Click to upload advert image">
  </div>

  <h4><%= f.label :title %> :</h4>
  <%= f.text_field :title, autofocus: true, required: true, class: "form-control"  %>
</div>

<div class="">
  <h4><%= f.label :description %>:</h4>
  <p><%= f.text_area :description,size: "100x5", required: true, class: "form-control" %> </p>
</div>

  <%= f.hidden_field :advert_image %>

<div class="center">
    <%= f.submit "Create", class: "btn btn-primary" %>
</div>

  <br>
<% end %>

</div>

app/views/adverts/index.html.erb
<div class="container center">

<h1>All Promos</h1>


<% @adverts.each do |advert| %>
<div class="card-group d-inline" style="width: 20%">

  <div class="card d-inline-block">

<% if advert.advert_image.to_s == "" %>
<%= image_tag 'http://i.imgur.com/hFjTK8K.png', size: "370x300" %>
 <%  else %>
 <%= image_tag advert.advert_image, size: "370x300" %>
<% end %>

<h3>Title: <%= advert.title %> </h3>

  <% if !advert.description %>
  <h4> Description : No description</h4>
  <p>Description:<%= advert.description %></p>
  <% elsif (advert.description.split.size >= 5) %>
  <h4> Description : <%= advert.description[/(\S+\s+){5}/].to_s.strip %>... </h4>
  <% else %>
  <h4> Description : <%= advert.description %></h4>
  <% end %>

  <p>Posted by:<%= advert.user.name %></p>

    <%= link_to "More details", advert_path(advert), class: "btn btn-primary" %>
</div>
</div>
<% end %>


</div>

app/views/adverts/new.html.erb
<h1>Create New Promo</h1>
<div class="container">

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<%= form_for @advert do |f| %>
<div class="field">

  <div class="center">
    <img class='advert_image' onclick="openEventWidgets()" src="http://i.imgur.com/hFjTK8K.png" data-toggle="tooltip" data-placement="right" title="Click to upload event image">
  </div>

  <h4><%= f.label :title %> :</h4>
  <%= f.text_field :title, autofocus: true, required: true, class: "form-control"  %>
</div>

<div class="">
  <h4><%= f.label :description %>:</h4>
  <p><%= f.text_area :description,size: "100x5", required: true, class: "form-control" %> </p>
</div>

  <%= f.hidden_field :advert_image %>

<div class="center">
    <%= f.submit "Create", class: "btn btn-primary" %>
</div>

  <br>
<% end %>

</div>

app/views/adverts/show.html.erb
<h1>Promo details</h1>

<% if @advert.advert_image.to_s != "" %>
<%= image_tag @advert.advert_image %>
<% else %>
<%= image_tag 'http://i.imgur.com/hFjTK8K.png', size: "370x300" %>
<% end %>

<h2><%= @advert.title %></h2>

<p><%= @advert.description %></p>

<% if @edit_advert_by_id == current_user.id %>
<div class="field">

  <%= link_to "Edit Promo", edit_advert_path, class: "btn btn-primary"  %>
</div>
<% end %>